### PR TITLE
/submissions: handle multipart parsing errors

### LINKED ISSUE #1432: 500 Error: Unexpected end of form
## Related

* https://github.com/getodk/central-backend/issues/1433
* https://github.com/getodk/central-backend/issues/1435

## Steps to recreate

```sh
curl 'https://staging.getodk.cloud/-/submission/Ih34Fbb2Tw3j5Eh2hrjWF82yVeJR6q4' \
  -H 'X-OpenRosa-Version: 1.0' \
  -H 'X-OpenRosa-Deprecated-Id: uuid:ee8b46a3-91c5-4e80-8aad-e9761d1ca874' \
  -H 'X-OpenRosa-Instance-Id: uuid:18f78460-81e2-4ddd-b723-499dce2618ca' \
  -H 'Content-Type: multipart/form-data; boundary=----geckoformboundary57597312afb59088b78af2a1fdc6038' \
  --data-binary $'------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="xml_submission_file"; filename="xml_submission_file"\r\nContent-Type: text/xml\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="__csrf"\r\n\r\nxxx\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="699-536x354-9_4_59.jpg"; filename="699-536x354-9_4_59.jpg"\r\nContent-Type: image/jpeg\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038--\r\n'
```

## Logs

```
service-1  | ::ffff:172.18.0.5 - - [11/Mar/2025:06:20:12 +0000] "HEAD /v1/projects/1/submission HTTP/1.0" 204 -
service-1  | Error: Malformed part header
service-1  |     at SBMH.ssCb [as _cb] (/usr/odk/node_modules/busboy/lib/types/multipart.js:398:32)
service-1  |     at SBMH.destroy (/usr/odk/node_modules/streamsearch/lib/sbmh.js:111:12)
service-1  |     at Multipart._final (/usr/odk/node_modules/busboy/lib/types/multipart.js:586:19)
service-1  |     at prefinish (node:internal/streams/writable:916:14)
service-1  |     at finishMaybe (node:internal/streams/writable:930:5)
service-1  |     at Writable.end (node:internal/streams/writable:845:5)
service-1  |     at IncomingMessage.onend (node:internal/streams/readable:948:10)
service-1  |     at Object.onceWrapper (node:events:638:28)
service-1  |     at IncomingMessage.emit (node:events:524:28)
service-1  |     at IncomingMessage.emit (node:domain:489:12)
service-1  |     at endReadableNT (node:internal/streams/readable:1698:12)
service-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
service-1  |   storageErrors: []
service-1  | }
service-1  | ::ffff:172.18.0.5 - - [11/Mar/2025:06:20:12 +0000] "POST /v1/projects/1/submission HTTP/1.0" 500 35
service-1  | Error: Unexpected end of form
service-1  |     at Multipart._final (/usr/odk/node_modules/busboy/lib/types/multipart.js:588:17)
service-1  |     at prefinish (node:internal/streams/writable:916:14)
service-1  |     at finishMaybe (node:internal/streams/writable:930:5)
service-1  |     at Writable.end (node:internal/streams/writable:845:5)
service-1  |     at IncomingMessage.onend (node:internal/streams/readable:948:10)
service-1  |     at Object.onceWrapper (node:events:638:28)
service-1  |     at IncomingMessage.emit (node:events:524:28)
service-1  |     at IncomingMessage.emit (node:domain:489:12)
service-1  |     at endReadableNT (node:internal/streams/readable:1698:12)
service-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
service-1  | Error: Unexpected end of form
service-1  |     at Multipart._final (/usr/odk/node_modules/busboy/lib/types/multipart.js:588:17)
service-1  |     at prefinish (node:internal/streams/writable:916:14)
service-1  |     at finishMaybe (node:internal/streams/writable:930:5)
service-1  |     at Writable.end (node:internal/streams/writable:845:5)
service-1  |     at IncomingMessage.onend (node:internal/streams/readable:948:10)
service-1  |     at Object.onceWrapper (node:events:638:28)
service-1  |     at IncomingMessage.emit (node:events:524:28)
service-1  |     at IncomingMessage.emit (node:domain:489:12)
service-1  |     at endReadableNT (node:internal/streams/readable:1698:12)
service-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:90:21)
service-1  | 2025-03-11T06:20:12: PM2 log: App name:service id:2 disconnected
service-1  | 2025-03-11T06:20:12: PM2 log: App [service:2] exited with code [1] via signal [SIGINT]
service-1  | 2025-03-11T06:20:12: PM2 log: App [service:2] starting in -cluster mode-
service-1  | 2025-03-11T06:20:12: PM2 log: App [service:2] online
```

It looks like this error may also crash the node process.

### LINKED ISSUE #1433: 500 Error: Malformed part header
## Related

* https://github.com/getodk/central-backend/issues/1432
* https://github.com/getodk/central-backend/issues/1435

## Steps to recreate

```sh
curl 'https://staging.getodk.cloud/-/submission/Ih34Fbb2Tw3j5Eh2hrjWF82yVeJR6q4' \
  -H 'X-OpenRosa-Version: 1.0' \
  -H 'X-OpenRosa-Deprecated-Id: uuid:ee8b46a3-91c5-4e80-8aad-e9761d1ca874' \
  -H 'X-OpenRosa-Instance-Id: uuid:18f78460-81e2-4ddd-b723-499dce2618ca' \
  -H 'Content-Type: multipart/form-data; boundary=----geckoformboundary57597312afb59088b78af2a1fdc6038' \
  --data-binary $'------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="xml_submission_file"; filename="xml_submission_file"\r\nContent-Type: text/xml\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="__csrf"\r\n\r\nxxx\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="699-536x354-9_4_59.jpg"; filename="699-536x354-9_4_59.jpg"\r\nContent-Type: image/jpeg\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038--\r\n\r\nhelo\r\n\r\n'
```

## Logs

```
service-1  | Error: Malformed part header
service-1  |     at SBMH.ssCb [as _cb] (/usr/odk/node_modules/busboy/lib/types/multipart.js:398:32)
service-1  |     at feed (/usr/odk/node_modules/streamsearch/lib/sbmh.js:248:10)
service-1  |     at SBMH.push (/usr/odk/node_modules/streamsearch/lib/sbmh.js:104:16)
service-1  |     at Multipart._write (/usr/odk/node_modules/busboy/lib/types/multipart.js:567:19)
service-1  |     at writeOrBuffer (node:internal/streams/writable:572:12)
service-1  |     at _write (node:internal/streams/writable:501:10)
service-1  |     at Writable.write (node:internal/streams/writable:510:10)
service-1  |     at IncomingMessage.ondata (node:internal/streams/readable:1009:22)
service-1  |     at IncomingMessage.emit (node:events:524:28)
service-1  |     at IncomingMessage.emit (node:domain:489:12)
service-1  |     at Readable.read (node:internal/streams/readable:782:10)
service-1  |     at flow (node:internal/streams/readable:1283:53)
service-1  |     at resume_ (node:internal/streams/readable:1262:3)
service-1  |     at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
service-1  |   storageErrors: []
service-1  | }
service-1  | ::ffff:172.18.0.5 - - [11/Mar/2025:06:21:40 +0000] "POST /v1/projects/1/submission HTTP/1.0" 500 35
```

### LINKED ISSUE #1435: 500 Error: Multipart: Boundary not found
## Related

* https://github.com/getodk/central-backend/issues/1432
* https://github.com/getodk/central-backend/issues/1433

## Steps to recreate

```sh
curl 'https://staging.getodk.cloud/-/submission/Ih34Fbb2Tw3j5Eh2hrjWF82yVeJR6q4' \
  -H 'X-OpenRosa-Version: 1.0' \
  -H 'X-OpenRosa-Deprecated-Id: uuid:ee8b46a3-91c5-4e80-8aad-e9761d1ca874' \
  -H 'X-OpenRosa-Instance-Id: uuid:18f78460-81e2-4ddd-b723-499dce2618ca' \
  -H 'Content-Type: multipart/form-data' \
  --data-binary $''
```

## Logs

```
service-1  | Error: Multipart: Boundary not found
service-1  |     at new Multipart (/usr/odk/node_modules/busboy/lib/types/multipart.js:233:13)
service-1  |     at getInstance (/usr/odk/node_modules/busboy/lib/index.js:33:12)
service-1  |     at module.exports (/usr/odk/node_modules/busboy/lib/index.js:56:10)
service-1  |     at multerMiddleware (/usr/odk/node_modules/multer/lib/make-middleware.js:28:16)
service-1  |     at Layer.handle [as handle_request] (/usr/odk/node_modules/express/lib/router/layer.js:95:5)
service-1  |     at next (/usr/odk/node_modules/express/lib/router/route.js:149:13)
service-1  |     at Route.dispatch (/usr/odk/node_modules/express/lib/router/route.js:119:3)
service-1  |     at Layer.handle [as handle_request] (/usr/odk/node_modules/express/lib/router/layer.js:95:5)
service-1  |     at /usr/odk/node_modules/express/lib/router/index.js:284:15
service-1  |     at param (/usr/odk/node_modules/express/lib/router/index.js:365:14)
service-1  |     at param (/usr/odk/node_modules/express/lib/router/index.js:376:14)
service-1  |     at Function.process_params (/usr/odk/node_modules/express/lib/router/index.js:421:3)
service-1  |     at next (/usr/odk/node_modules/express/lib/router/index.js:280:10)
service-1  |     at cookieParser (/usr/odk/node_modules/cookie-parser/index.js:57:14)
service-1  |     at Layer.handle [as handle_request] (/usr/odk/node_modules/express/lib/router/layer.js:95:5)
service-1  |     at trim_prefix (/usr/odk/node_modules/express/lib/router/index.js:328:13)
service-1  | ::ffff:172.18.0.5 - - [11/Mar/2025:06:29:03 +0000] "POST /v1/projects/1/submission HTTP/1.0" 500 35
```

### PR DESCRIPTION
**Pull request by alxndrsn**
Errors from multer/busboy were previously unhandled, and would result in various 500 errors.

Closes #1432
Closes #1433
Closes #1435

#### What has been done to verify that this works as intended?

Fresh tests.

#### Why is this the best possible solution? Were any other approaches considered?

Considered also adding handling for `err instanceof multer.MulterError`, but I could not trigger any of those errors.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should prevent 500 errors, which hopefully no users are relying on.  This error has not been seen in production.

#### Does this change require updates to the API documentation? If so, please update docs/api.yaml as part of this PR.

No.

#### Before submitting this PR, please make sure you have:

- [x] run `make test` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: lib/resources/submissions.js [hunk 1]
```diff
@@ -46,6 +46,25 @@ const findMultipart = (files) => {
 };
 const forceAuthFailed = Problem.translate(Problem.user.insufficientRights, Problem.user.authenticationFailed);
 
+// The following errors bubble up through multer from busboy, and are generic Error objects:
+const busboyErrors = [
+  'Malformed part header',
+  'Malformed content type',
+  'Malformed part header',
```
Comment (matthew-white) [inline lib/resources/submissions.js:53]: This one looks to be a duplicate.

File: lib/resources/submissions.js [hunk 2]
```diff
@@ -82,7 +101,7 @@ module.exports = (service, endpoint) => {
     };
 
     // Nonstandard REST; OpenRosa-specific API.
-    service.post(path, multipart.any(), multerUtf, endpoint.openRosa(({ Forms, Submissions, SubmissionAttachments }, { params, files, auth, query, userAgent }) =>
+    service.post(path, multipart.any(), multerUtf, multipartErrorHandler, endpoint.openRosa(({ Forms, Submissions, SubmissionAttachments }, { params, files, auth, query, userAgent }) =>
```
Comment (matthew-white) [inline lib/resources/submissions.js:104]: Could you say a little about why this is the only endpoint that needs this error handler? Is it because this endpoint is the only one that uses multer?

File: lib/resources/submissions.js [hunk 3]
```diff
@@ -46,6 +46,25 @@ const findMultipart = (files) => {
...
+  'Malformed part header',
+  'Malformed urlencoded form',
+  'Missing Content-Type',
+  'Multipart: Boundary not found',
+  'Unexpected end of file',
+  'Unexpected end of form',
+];
+const multipartErrorHandler = (err, req, res, next) => {
+  if (busboyErrors.includes(err.message) || err.message.startsWith('Unsupported content type: ')) {
+    next(Problem.user.multipartParsingFailed());
```
Comment (matthew-white) [inline lib/resources/submissions.js:62]: How about passing `err.message` to `Problem.user.multipartParsingFailed()` so that it can be included in the `details` object of the Problem response? If we have this extra information about what exactly went wrong, I figure we might as well return it to the user.

File: test/integration/api/submissions.js [hunk 4]
```diff
@@ -53,6 +53,47 @@ describe('api: /submission', () => {
...
+              message: 'Multipart form content failed to parse.',
+            });
+          }))));
+
+    it('should reject if "Malformed part header"', testService((service) =>
+      service.login('alice', (asAlice) =>
+        asAlice.post('/v1/projects/1/submission')
+          .set('X-OpenRosa-Version', '1.0')
+          .set('Content-Type', 'multipart/form-data; boundary=----geckoformboundary57597312afb59088b78af2a1fdc6038')
+          .send('------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="xml_submission_file"; filename="xml_submission_file"\r\nContent-Type: text/xml\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="__csrf"\r\n\r\nxxx\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038\r\nContent-Disposition: form-data; name="699-536x354-9_4_59.jpg"; filename="699-536x354-9_4_59.jpg"\r\nContent-Type: image/jpeg\r\n\r\n------geckoformboundary57597312afb59088b78af2a1fdc6038--\r\n\r\nhelo\r\n\r\n')
```
Comment (matthew-white) [inline test/integration/api/submissions.js:88]: I can't quite tell right away, what's wrong about this payload? How about adding a comment to the test?

**Review by matthew-white — APPROVED** [review]

File: lib/resources/submissions.js (hunk 2 above)
Comment (alxndrsn) [reply lib/resources/submissions.js:103]: Yes.  A few of suggestions to improve clarity:

1. colocate `multipart` and `multipartErrorHandler` in this file
2. colocate `multipart` and `multipartErrorHandler` in e.g. `utils/multipart.js`
3. add a comment above `multipart` like `NOTE always use in conjunction with multipartErrorHandler`

Would any of these help?

Comment (alxndrsn) [reply lib/resources/submissions.js:104]: I've gone with #1 for now.
