### PR TITLE
cypto.getPrivate(): fix error when passphrase kinda works

### LINKED ISSUE #1212: Intermittent test failure: DECODER routines::unsupported
https://github.com/getodk/central-backend/actions/runs/10702632292/job/29671272325

```
2024-09-04T13:27:47.9903658Z   managed encryption
2024-09-04T13:27:47.9904491Z     lock management
2024-09-04T13:27:48.2104194Z       ✔ should reject keyless forms in keyed projects @slow (221ms)
2024-09-04T13:27:49.0429483Z       ✔ should reject forms created while project managed encryption is being enabled @slow (184ms)
2024-09-04T13:27:49.6529419Z     decryptor
2024-09-04T13:27:50.0331955Z       ✔ should give a decryptor for the given passphrases (380ms)
2024-09-04T13:27:50.0333106Z     encrypted submission attachment parsing
2024-09-04T13:27:50.0344764Z       ✔ should correctly record attachment file ordering
2024-09-04T13:27:50.0347678Z     end-to-end
2024-09-04T13:27:50.0410796Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/sessions HTTP/1.1" 200 228
2024-09-04T13:27:50.2878107Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/key HTTP/1.1" 200 16
2024-09-04T13:27:50.2907190Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple.xml HTTP/1.1" 200 1285
2024-09-04T13:27:50.2980087Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/forms/simple/submissions HTTP/1.1" 200 305
2024-09-04T13:27:50.3029627Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "POST /v1/projects/1/forms/simple/submissions/one/attachments/submission.xml.enc HTTP/1.1" 200 16
2024-09-04T13:27:50.3062329Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple/submissions/keys HTTP/1.1" 200 492
2024-09-04T13:27:50.3429563Z Error: error:1E08010C:DECODER routines::unsupported
2024-09-04T13:27:50.3430688Z     at createPrivateKey (node:internal/crypto/keys:632:12)
2024-09-04T13:27:50.3432370Z     at /home/runner/work/central-backend/central-backend/lib/util/crypto.js:156:14
2024-09-04T13:27:50.3433409Z     at async Promise.all (index 0) {
2024-09-04T13:27:50.3433866Z   library: 'DECODER routines',
2024-09-04T13:27:50.3434488Z   reason: 'unsupported',
2024-09-04T13:27:50.3435064Z   code: 'ERR_OSSL_UNSUPPORTED'
2024-09-04T13:27:50.3435810Z }Error: error:1E08010C:DECODER routines::unsupported
2024-09-04T13:27:50.3436874Z     at createPrivateKey (node:internal/crypto/keys:632:12)
2024-09-04T13:27:50.3438123Z     at /home/runner/work/central-backend/central-backend/lib/util/crypto.js:156:14
2024-09-04T13:27:50.3439090Z     at async Promise.all (index 0) {
2024-09-04T13:27:50.3439738Z   library: 'DECODER routines',
2024-09-04T13:27:50.3440302Z   reason: 'unsupported',
2024-09-04T13:27:50.3440860Z   code: 'ERR_OSSL_UNSUPPORTED'
2024-09-04T13:27:50.3443347Z ::ffff:127.0.0.1 - - [04/Sep/2024:13:27:50 +0000] "GET /v1/projects/1/forms/simple/submissions.csv.zip?4=wrong HTTP/1.1" 500 35
2024-09-04T13:27:50.3452770Z       1) should reject with a reasonable message given incorrect passphrase
```

```
  2437 passing (2m)
  20 pending
  1 failing

  1) managed encryption
       end-to-end
         should reject with a reasonable message given incorrect passphrase:
     Error: expected 400 "Bad Request", got 500 "Internal Server Error"
      at /home/runner/work/central-backend/central-backend/test/integration/other/encryption.js:204:14
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Object.transaction (node_modules/slonik/dist/src/connectionMethods/transaction.js:22:24)
      at async Object.createConnection (node_modules/slonik/dist/src/factories/createConnection.js:97:18)
  ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at /home/runner/work/central-backend/central-backend/node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)
      at Object.onceWrapper (node:events:628:28)
      at Server.emit (node:events:514:28)
      at Server.emit (node:domain:488:12)
      at emitCloseNT (node:net:2273:8)
      at process.processTicksAndRejections (node:internal/process/task_queues:81:21)



    at process.processImmediate (node:internal/timers:478:21)make: *** [Makefile:58: test] Error 1
```

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #1212

Sometimes an incorrect passphrase can still "successfully" decrypt supplied the supplied ciphertext, but to nonsense.  In this case, the call to `createPrivateKey()` will throw an error that was not previously handled by the surrounding try/catch block.

#### What has been done to verify that this works as intended?

Added tests.

#### Why is this the best possible solution? Were any other approaches considered?

The full error generated can be:

```
Error: error:1E08010C:DECODER routines::unsupported
    at createPrivateKey (node:internal/crypto/keys:726:12)
    at /home/user/workspaces/odk/backend/lib/util/crypto.js:164:14 {
  opensslErrorStack: [ 'error:1E08010C:DECODER routines::unsupported' ],
  library: 'DECODER routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_UNSUPPORTED'
}
```

Checking `error.code` seems like it should be reasonably stable.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should reduce 500 errors or similar.

#### Does this change require updates to the API documentation? If so, please update docs/api.yaml as part of this PR.

Hopefully not.

#### Before submitting this PR, please make sure you have:

- [x] run `make test` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: test/unit/util/crypto.js [hunk 1]
```diff
@@ -135,6 +136,46 @@ describe('util/crypto', () => {
...
+      },
+    ].forEach((keys, idx) => {
+      it(`should generate private key from example #${idx} with correct passphrase`, async () => {
+        const res = await getPrivate(keys, 'supersecret');
+        (res instanceof KeyObject).should.be.true();
+      });
+
+      [
+        'wrong',
+        'very-wrong',
```
Comment (matthew-white) [inline test/unit/util/crypto.js:163]: Is there a difference between these two cases? E.g., is one an example of `ERR_OSSL_UNSUPPORTED`? If so, I think a comment could be helpful.

**Review by matthew-white — APPROVED** [review]
Looks great, it sounds like this is getting to the root cause of the issue.

**Comment by matthew-white** [comment]
I'm going to take this PR out of the project, since the associated issue is also in the project.

File: test/unit/util/crypto.js (hunk 1 above)
Comment (alxndrsn) [reply test/unit/util/crypto.js]: Good suggestion - comments added.
