### PR TITLE
Standardise responses for invalid user email

### LINKED ISSUE #1430: "500: Unexpected value expression" with unexpected email type
```sh
$ curl localhost:8383/v1/sessions -H 'content-type: application/json' --data '{"password":"helo", "email":{}}'
{"message":"Internal Server Error"}
```

Related:

* https://github.com/getodk/central-backend/issues/1406
* https://github.com/getodk/central-backend/issues/1407
* https://github.com/getodk/central-backend/pull/1411
* https://github.com/getodk/central-backend/pull/1410

### PR DESCRIPTION
**Pull request by alxndrsn**
Closes #1430

#### What has been done to verify that this works as intended?

* existing tests
* new tests

#### Why is this the best possible solution? Were any other approaches considered?

Validation of the `email` type could be performed closer to the API.  In that case, validations should be added in more places.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should reduce number of 500 errors.  Users are unlikely to be relying on this status code.

#### Does this change require updates to the API documentation? If so, please update docs/api.yaml as part of this PR.

500 errors should not be documented, so no documentation update is expected.

#### Before submitting this PR, please make sure you have:

- [x] run `make test` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

**Review by sadiqkhoja — APPROVED** [review]

File: lib/model/query/users.js [hunk 1]
```diff
@@ -73,7 +74,8 @@ ${page(options)}`;
 const getAll = (options) => ({ all }) => all(_getSql(options)).then(map(_unjoin));
 
 const getByEmail = (email, options = QueryOptions.none) => ({ maybeOne }) =>
-  maybeOne(_getSql(options.withCondition({ email }))).then(map(_unjoin));
+  rejectUnless('string')({ email })
+    .then(() => maybeOne(_getSql(options.withCondition({ email }))).then(map(_unjoin)));
```
Comment (alxndrsn) [inline lib/model/query/users.js:78]: @matthew-white does this seem idiomatic?

Comment (matthew-white) [reply lib/model/query/users.js:78]: Are you wondering about the new `rejectUnless()` function? It looks similar to other functions in lib/util/promise.js, so it seems reasonable to me.

Though that said, some of those functions actually feel slightly awkward to me when used outside a promise chain. When issa first introduced those functions, we almost never used `async`/`await`. But now we tend to use `async`/`await` where possible/convenient, and in that context, these promise utility functions end up becoming double function calls like what you have here with `rejectUnless()`. Those aren't my personal favorite, though I also don't think it's a big deal.

One thing I've thought about is that we could modify these functions so that they could work as either a single call or a double call, e.g., `rejectUnless('string', { email })` would be equivalent to `rejectUnless('string')({ email })`. I think the Ramda `curry()` function would let us do that pretty easily. `rejectUnless('string')` would be very convenient in a promise chain, when we want a function to pass to `.then()`. While in the context of `async`/`await`, I think `rejectUnless('string', { email })` is a little nicer.

Anyway, that's mostly just my own thoughts / not something we've discussed a lot. But I did want to mention the larger context of transitioning to more `async`/`await`. I'm pretty sure we all prefer `async`/`await`, but the codebase has a history of a lot of `.then()`.

Comment (alxndrsn) [reply lib/model/query/users.js:78]: > some of those functions actually feel slightly awkward to me when used outside a promise chain

I agree, especially this new `rejectUnless()()`.  I also think the name is too generic for such a specific validation function.  I've inlined and rewritten the line in a way that looks in-keeping with the existing promise-chain style:

```diff
-  rejectUnless('string')({ email })
+  resolve(rejectIf(compose(not, is(String)), () => Problem.user.invalidDataTypeOfParameter({ field: 'email', expected: 'string' }))(email))
```

I think the function could be rewritten with considerable readability improvement as:

```js
const getByEmail = (email, options = QueryOptions.none) => ({ maybeOne }) => {
  assertString('email', email);
  return maybeOne(_getSql(options.withCondition({ email }))).then(map(_unjoin));
};
```

Comment (matthew-white) [reply lib/model/query/users.js:79]: I agree, I definitely find the second version more readable/preferable.
