### PR TITLE
fixes #666: dataset and property has publishedAt

### LINKED ISSUE #666: Purging forms and submissions that create entities
When a form is purged, it purges the submissions associated with that form. Entities have a `submissionDefId` foreign key that links back to the source submission def, but that foreign key constraint will be violated when the submission is purged. We will change this by allowing the submission def ID to be set to null on the entity. Matt left a comment and example test [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301611258).

Form purging also affects how the dataset draft endpoints work. Currently, much of the state about a dataset and its properties is inferred from the state of the forms that contribute properties to that dataset. We will add `publishedAt` flags to the datasets themselves and the dataset properties to be a bit more explicit about when properties or whole datasets became available, and rely less on the state of the forms themselves in case they get deleted purged. More notes [here](https://github.com/getodk/central-backend/issues/649#issuecomment-1301627820).

Conceptually, datasets and entities exist in a different realm than forms and submissions. While a form and its submissions get deleted, datasets and entities wont get deleted, though the link between them will be broken. We'll come back to dataset and entity deletion soon.

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Closes #666 

#### What has been done to verify that this works as intended?
- Added integration tests
- Performed manual testing with frontend

#### Why is this the best possible solution? Were any other approaches considered?
Previous solution of having implicit status for dataset and its properties was not working, especially when form gets purged

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?
I guess whole dataset/entities feature should be tested

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.
NA

#### Before submitting this PR, please make sure you have:

- [x] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments

### CODE REVIEW

File: lib/model/query/forms.js [hunk 1]
```diff
@@ -258,6 +262,13 @@ with redacted_audits as (
     left outer join form_defs on coalesce(forms."currentDefId", forms."draftDefId") = form_defs.id
     where actees.id = forms."acteeId"
     and ${_trashedFilter(force, id, projectId)}
+  ), update_entities as (
```
Comment (ktuite) [inline lib/model/query/forms.js:265]: if we change the migration above to "on delete set null", then wont this just happen automatically?

File: lib/model/migrations/20221114-01-explict-dataset-publish.js [hunk 2]
```diff
@@ -0,0 +1,38 @@
...
+// https://github.com/getodk/central-backend/blob/master/NOTICE.
+// This file is part of ODK Central. It is subject to the license terms in
+// the LICENSE file found in the top-level directory of this distribution and at
+// https://www.apache.org/licenses/LICENSE-2.0. No part of ODK Central,
+// including this file, may be copied, modified, propagated, or distributed
+// except according to the terms contained in the LICENSE file.
+
+const up = async (db) => {
+  await db.schema.table('entity_defs', (eDef) => {
+    eDef.integer('submissionDefId').alter({ nullable: true });
```
Comment (ktuite) [inline lib/model/migrations/20221114-01-explict-dataset-publish.js:12]: In addition to setting this to nullable, I was thinking you could set this onDelete command. This is like my strategy in `./20220121-01-form-cascade-delete.js` but using `.onDelete('set null')` instead of `.onDelete('cascade')`:
```
eDef.dropForeign('submissionDefId');
eDef.foreign('submissionDefId').references('submission_defs.id').onDelete('set null');
```

File: lib/model/query/forms.js [hunk 3]
```diff
@@ -159,12 +161,14 @@ createVersion.audit.withResult = true;
...
-const publish = (form) => ({ Forms }) => {
+const publish = (form) => ({ Forms, Datasets }) => {
   if (form.draftDefId !== form.def.id) throw Problem.internal.unknown();
 
+  const publishedAt = (new Date()).toISOString();
   return Promise.all([
     Forms._update(form, { currentDefId: form.draftDefId, draftDefId: null }),
-    Forms._updateDef(form, { draftToken: null, enketoId: null, publishedAt: (new Date()).toISOString() })
+    Forms._updateDef(form, { draftToken: null, enketoId: null, publishedAt }),
+    Datasets.publish(form.def.id, publishedAt)
```
Comment (ktuite) [inline lib/model/query/forms.js:171]: A question that might be better for an interactive review: this will be called for every form when it gets published so I just wanted to make sure this wouldn't have any negative effects if called on a form without any datasets. Maybe it could have a more non-committal name like "Datasets.publishIfPresent", "maybePublish", "possiblyPublish"... or could we check `entityRelated` on the form and only conditional run this?

**Review by ktuite — COMMENTED** [review]
Took a quick async look late Tuesday night and left a few comments. Will do a more thorough review on Wedneday.

**Comment by matthew-white** [comment]
I'll let @ktuite take a look, but let me know if there's anything you want me to look at here!

One question I had was about backfilling. If a database already has a dataset, then after this PR, I think that dataset will have a `null` `publishedAt`, so won't be listed in &hellip;/datasets. I think that's reasonable, but I just wanted to make sure that that's the expectation.

File: lib/model/query/forms.js (hunk 3 above)
Comment (sadiqkhoja) [reply lib/model/query/forms.js:171]: just realized, I have to add audit logs for publish as well

Comment (matthew-white) [reply lib/model/query/forms.js:171]: You two may have discussed this already, but I think we'll also need to add this new audit action to Frontend.

Comment (sadiqkhoja) [reply lib/model/query/forms.js:171]: yes, I have added it in https://github.com/getodk/central-frontend/pull/641

Comment (sadiqkhoja) [reply lib/model/query/forms.js]: renamed publish function to publishIfExists
