### PR TITLE
enhances #722: add ability to select parentID

### LINKED ISSUE #722: OData $select: add ability to select __parent-table-id
OData `$metadata` document shows parent table ID like `__submission-id` as a field for the subtables but selecting it returns 400 error.

Excel OData feed uses metadata document to determine the valid fields for the table and then makes request with $select query parameter. Right now request with $select for subtables are failing with 400 error and Excel falls back to requesting without $select

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Closes #722 

#### What has been done to verify that this works as intended?

Added integration test
Manually verified via Excel and checked logs 

#### Why is this the best possible solution? Were any other approaches considered?

NA

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

NA

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.

NA

#### Before submitting this PR, please make sure you have:

- [x] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: lib/formats/odata.js [hunk 1]
```diff
@@ -527,42 +527,55 @@ const filterFields = (formFields, select, table) => {
...
     }
+    parentIdKey += '-id';
+    idKeys.add(parentIdKey);
   }
 
   for (const property of select.split(',').map(p => p.trim())) {
     // validate metadata properties. __system/.. properties are only valid for Submission table
-    if (property.startsWith('__id') || property.startsWith('__system')) {
-      if (!(property === '__id' || (table === 'Submissions' && systemFields.has(property))))
-        throw Problem.user.propertyNotFound({ property });
```
Comment (matthew-white) [inline lib/formats/odata.js:543]: Could you add a test that `$select`-ing a `__system` property for a subtable results in a 404 response? This `if` used to handle it, but now it's handled by different logic after the `continue`.

**Review by matthew-white — APPROVED** [review]

**Comment by matthew-white** [comment]
I think @sadiqkhoja would know best, but I feel like it's probably safe to include this in the patch. Only OData should be affected by this change, and OData tests continue to pass. Sadiq also verified things manually in Excel.

**Comment by sadiqkhoja** [comment]
This is safe to release in the patch, I have performed sanity test on staging after the merge as well
