### PR TITLE
oidc: pass state to IdP in authorization URL

### LINKED ISSUE #1134: OIDC login fails due to Authentik sending state QS and node-openid-client failing a check
It's all here.  https://forum.getodk.org/t/oidc-issue-when-logging-in/46619

### PR DESCRIPTION
**Pull request by alxndrsn**
* pass `next` value to IdP as `state`, with additional random prefix
* this makes the "next" value more trusted
* fix support for Authentik and other IdPs which do not support auth URLs without `state` (https://github.com/goauthentik/authentik/pull/9735)
* may also improve support for IdPs which lack PKCE support (see: https://github.com/panva/openid-client/blob/1486c3a020af8d12449d1d6a4bdf4f2bf4d32b77/README.md#authorization-code-flow)

Closes #1134
Closes #1135

#### What has been done to verify that this works as intended?

- [x] test with `fake-oidc-server`
- [x] test with google oauth

#### Why is this the best possible solution? Were any other approaches considered?

Alternative: separate `state` & `next` cookies in https://github.com/getodk/central-backend/pull/1135

The approach in this PR is an improvement on that as it prevents tampering with the `next` cookie, e.g. by cookie tossing.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

Should only affect users integrated with Authentik, which should now work.

#### Does this change require updates to the API documentation? If so, please update docs/api.yaml as part of this PR.

No.

#### Before submitting this PR, please make sure you have:

- [x] run `make test` and confirmed all checks still pass OR confirm CircleCI build passes
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: lib/resources/oidc.js [hunk 1]
```diff
@@ -105,17 +108,19 @@ module.exports = (service, endpoint) => {
 
       const code_challenge = generators.codeChallenge(code_verifier); // eslint-disable-line camelcase
 
+      const { next } = req.query ?? '';
```
Comment (alxndrsn) [inline lib/resources/oidc.js:111]: This may not do what it intends to... I suspect this is different to:

```js
const next = req.query.next ?? '';
```

Maybe add a test for `next` missing, if that's a possible situation.
