### PR TITLE
fixes 911: delete draft submission on project encryption

### LINKED ISSUE #911: Issues with draft submissions after project encryption
From the QA team while completing regression testing for v2023.3:

<blockquote>
Disappearing submissions in draft testing after the project becomes encrypted.
Steps to reproduce:

- Add a new draft version of a form
- Go to the Testing tab and add a submission (click “+New” and submit a form)
- Go to the project overview, Settings and enable encryption
- Go back to the Draft of the form and add another submission
- Check the submission table and download the CSV
</blockquote>
<br>

<br>
<br>

These screenshots seem to be from this page: https://test.getodk.cloud/#/projects/451/forms/geojson/draft/testing. It's interesting that the submission count is 3 (on the download button, in the row number), yet only 1 submission is shown. Similarly at https://test.getodk.cloud/#/projects/469/forms/geojson/draft/testing, the submission count is 2, yet no submissions are shown.

@sadiqkhoja was able to reproduce this behavior using v2022.3.1, so it doesn't seem like a regression in the upcoming v2023.3.

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Closes #911

#### What has been done to verify that this works as intended?

Integration and manual test

#### Why is this the best possible solution? Were any other approaches considered?

Please see the discussion on the issue.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

None

#### Does this change require updates to the API documentation? If so, please update docs/api.md as part of this PR.

NA

#### Before submitting this PR, please make sure you have:

- [x] run `make test-full` and confirmed all checks still pass OR confirm CircleCI build passes
- [ ] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: lib/model/query/submissions.js [hunk 1]
```diff
@@ -116,6 +116,8 @@ update.audit = (form, submission, data) => (log) => log('submission.update', for
 const clearDraftSubmissions = (formId) => ({ run }) =>
   run(sql`delete from submissions where "formId"=${formId} and draft=true`);
 
+const clearDraftSubmissionsForProject = (projectId) => ({ run }) =>
+  run(sql`DELETE FROM submissions USING forms WHERE submissions."formId" = forms.id AND forms."projectId" = ${projectId} AND submissions.draft=true`);
```
Comment (matthew-white) [inline lib/model/query/submissions.js:120]: It looks like deleted forms aren't encrypted (#945), yet this will delete the draft submissions of deleted forms. I don't think that's a big deal, and I don't think this function should change, but I thought I'd make a note of it.

**Review by matthew-white — APPROVED** [review]
