### PR TITLE
Fixes: Exclude deleted properties from the SQL query for geojson

### LINKED ISSUE #1769: Duplicate in the Entity GeoJSON representation API response
Hello!

I just installed version **2026.1.0** and it seems there is a duplicate in the API response that retrieves the geometry in GeoJSON format.

The endpoint `GET /v1/projects/{projectId}/datasets/{name}/entities/{uuid}/geojson` returns a FeatureCollection type **with 2 features of the same geometry**.

Similarly, when entities are displayed on the map from the front, the entity counter **counts twice as many entities**.

Thank you for all the work you've done!

### PR DESCRIPTION
**Pull request by sadiqkhoja**
Closes getodk/central#1769

#### What has been done to verify that this works as intended?

Added tests and manual verification

#### Why is this the best possible solution? Were any other approaches considered?

Fixes the issue. Other option is to remove the join with `ds_properties` altogether because I don't think it is possible to create an entity with the data that includes non-existent properties.

I think similar fix is required in `getDatasetProperties` of `analytics.js`. Will create a separate PR for that if required.

#### How does this change affect users? Describe intentional changes to behavior and behavior that could have accidentally been affected by code changes. In other words, what are the regression risks?

No

#### Does this change require updates to the API documentation? If so, please update docs/api.yaml as part of this PR.

No

#### Before submitting this PR, please make sure you have:

- [x] run `make test` and confirmed all checks still pass, or witnessed Github completing all checks with success
- [x] verified that any code from external sources are properly credited in comments or that everything is internally sourced

### CODE REVIEW

File: lib/model/query/geo-extracts.js [hunk 1]
```diff
@@ -184,6 +184,10 @@ const getEntityFeatureCollectionGeoJson = (datasetPK, odataQuery, limit=null, se
                 ds.id = ${datasetPK}
                 AND
                 (dsprops.name, dsprops."datasetId") = ('geometry', ds.id)
+                AND
+                dsprops."deletedAt" IS NULL
+                AND
+                dsprops."publishedAt" IS NOT NULL
```
Comment (sadiqkhoja) [inline lib/model/query/geo-extracts.js:190]: adding `publishedAt` clause is not strictly necessary to add. I couldn't think of any case where it might cause similar problem because we don't have ability to unpublish a property. At the same time I think there is no harm in adding the clause here. I am open to remove it if there is any objection.

**Review by ktuite — APPROVED** [review]

**Comment by sadiqkhoja** [comment]
talked with @ktuite on Slack and decided that we don't need to change analytics queries for now.

**Comment by sadiqkhoja** [comment]
Waiting for @brontolosone 's opinion on removing `ds_properties` join, otherwise this PR is ready to be merged.

File: lib/model/query/geo-extracts.js (hunk 1 above)
Comment (brontolosone) [reply lib/model/query/geo-extracts.js:190]: Better safe than sorry. If the DB allows for expressing something, it's worth guarding against it if it'd cause problems.
